services:
  app:
    build: ./zero2prod-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    profiles: ["default"]

  db:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data:/var/tmp/data-ingestion
    profiles: ["default", "db-standalone"]

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8081:8080
    profiles: ["db-standalone"]

volumes:
  pgdata:
