services:
  app:
    build: ./zero2prod-app
    restart: unless-stopped
    ports:
      - "8080:8080"

  db:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data

# leave this commented out, not needed for now
#  adminer:
#    image: adminer
#    restart: unless-stopped
#    ports:
#      - 8080:8081

volumes:
  pgdata:
