name: "Rust test, fmt and linting"

on:
  push:
    branches: [ "main" , "feature/**" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:

  test:
    name: Cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Cargo test
        working-directory: zero2prod-app
        run: cargo test --all-features

  formatting:
    name: Cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Cargo fmt
        working-directory: zero2prod-app
        run: cargo fmt --check

  clippy:
    name: Cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - name: Cargo clippy
        working-directory: zero2prod-app
        run: cargo clippy -- -D warnings
